APPLICATION = am2301-lcd0802
BOARD ?= arduino-nano
RIOTBASE ?= $(CURDIR)/../drivers_dht/RIOT

USEMODULE += hd44780
CFLAGS += '-DHD44780_PARAM_COLS=8'
CFLAGS += '-DHD44780_PARAM_ROWS=2'
CFLAGS += '-DHD44780_PARAM_PIN_RS=GPIO_PIN(PORT_C,0)'
CFLAGS += '-DHD44780_PARAM_PIN_ENABLE=GPIO_PIN(PORT_C,1)'
CFLAGS += '-DHD44780_PARAM_PINS_DATA={\
	GPIO_PIN(PORT_C,2),\
	GPIO_PIN(PORT_C,3),\
	GPIO_PIN(PORT_C,4),\
	GPIO_PIN(PORT_C,5),\
	GPIO_UNDEF,GPIO_UNDEF,GPIO_UNDEF,GPIO_UNDEF\
}'
USEMODULE += dht
CFLAGS += '-DDHT_PARAM_PIN=GPIO_PIN(PORT_B,0)'
CFLAGS += '-DDHT_PARAM_TYPE=AM2301'

include $(RIOTBASE)/Makefile.include
